baseURL = "http://example.org/"
languageCode = "en-gb"
title = "wheelibin.co.uk"

SectionPagesMenu = "main"

[params]
  custom_css = ["css/custom.css"]
  Description = "assorted rubbish"

[markup]
  [markup.highlight]
    # style = "doom-one"
    # style = "catppuccin-macchiato"
    style = "nord"
