baseURL = "https://wheelibin.github.io/wheelibin.co.uk"
languageCode = "en-gb"
title = "wheelibin.co.uk"

SectionPagesMenu = "main"
canonifyurls = "true"

[params]
  custom_css = ["css/header_footer.css","css/site.css"]
  Description = "assorted rubbish"

[markup]
  [markup.highlight]
    # style = "doom-one"
    # style = "catppuccin-macchiato"
    style = "nord"
